### ISSUE TITLE
[Bug] "stream has already been operated upon or closed" exception occurs when executing 

### ISSUE THREAD

**Issue by this** [Niveathika92/siddhi-execution-rdbms#1]
**Description:**
`java.lang.IllegalStateException: stream has already been operated upon or closed` is thrown from the `RDBMSStreamProcessorUtil.queryContainsCheck()` method when this extension is invoked.

Cause of the said exception is explain in [this blog](https://www.mkyong.com/java8/java-stream-has-already-been-operated-upon-or-closed/). 

**Suggesting Fix:**
```java
    public static boolean queryContainsCheck(String query) {
        return query.contains("DROP") || query.contains("ALTER");
    }
```

**Comment by niveathika** [comment]
Fixed after refactoring of the extension
